# Generated by Django 2.2 on 2021-03-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_quote'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
            ],
        ),
    ]
