# Generated by Django 2.2 on 2021-03-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birhday',
            new_name='birthday',
        ),
    ]
