# Generated by Django 2.2 on 2021-03-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210316_2150'),
        ('wall_app', '0002_auto_20210317_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='login_app.User'),
        ),
    ]
