# Generated by Django 2.2 on 2021-03-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20210317_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='poster',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='poster',
            new_name='user',
        ),
    ]
