# Generated by Django 2.2 on 2021-03-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210316_2150'),
        ('wall_app', '0006_auto_20210318_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='login_app.User'),
        ),
    ]
